# Generated by Django 5.1.3 on 2025-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('facilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
