# Generated by Django 4.2.7 on 2025-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RenameField(
            model_name='host',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='host',
            name='address',
        ),
        migrations.RemoveField(
            model_name='host',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='host',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='description',
        ),
        migrations.RemoveField(
            model_name='host',
            name='hosting_since',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='host',
            name='total_properties',
        ),
        migrations.RemoveField(
            model_name='host',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='host',
            name='verification_documents',
        ),
        migrations.AddField(
            model_name='host',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='hosts/'),
        ),
    ]
